Makisheva/UI tests
Narodni-repozitar/nr-docs pull request #104
Opened 2024-04-26 13:01 UTC by AlbinaMakisheva

2024-05-23 14:39 UTC, mirekys submitted a review, later dismissed

2024-05-24 11:15 UTC, mirekys requested changes

2024-06-06 10:25 UTC, mirekys requested changes
Fix sonar issues

2024-06-06 10:27 UTC, mirekys requested changes

2024-06-06 10:27 UTC, mirekys commented on tests/ui/util.js
Why do all of this crypto-dance when only a simple random number is needed? 😅

2024-06-06 10:30 UTC, AlbinaMakisheva commented on tests/ui/util.js
Math.random caused issues in sonar with high level of danger

2024-06-06 10:33 UTC, mirekys commented on tests/ui/create-form.spec.ts
> +      .dblclick();
Now will be single-click

2024-06-06 11:02 UTC, mirekys requested changes

2024-06-06 11:02 UTC, mirekys commented on tests/ui/dashboard.spec.ts
> +  await expect(page.getByTestId("aggregation-count")).toContainText("20");
Where does that 20 records come from?

2024-06-06 11:30 UTC, AlbinaMakisheva commented on tests/ui/util.js
https://rules.sonarsource.com/javascript/tag/cwe/RSPEC-2245/

2024-06-06 15:38 UTC, mirekys commented on tests/ui/util.js
Is it really a security risk, when someone could (given some non-trivial effort) guess which item will be randomly clicked on, while the test scenario is executed by CI?

2024-06-11 10:14 UTC, mirekys commented on tests/ui/dashboard.spec.ts
> +  await expect(page.getByTestId("aggregation-count")).toContainText("20");
What is this "aggregation-count" element? Is it count of items in some aggregation value? Or result count?

2024-06-12 10:17 UTC, mirekys submitted a review, later dismissed

2024-06-12 13:39 UTC, AlbinaMakisheva commented
@mirekys I fixed a conflict with main, so one more approval is required

2024-06-13 11:44 UTC, merged