Unifying administrator role with administration action, adding commun…
Narodni-repozitar/nr-docs pull request #161
Opened 2024-09-08 17:05 UTC by mesemus

…ity policies

2024-10-08 10:52 UTC, mirekys requested changes

2024-10-08 10:52 UTC, mirekys commented on common/services/communities/permissions.py
> +    # can_read = [
Cleanup commented out code

2024-10-08 10:52 UTC, mirekys commented on common/services/communities/permissions.py
> +    #
Cleanup commented out code

2024-11-11 11:25 UTC, closed without merging

2024-11-11 11:25 UTC, mesemus commented
merged into  miroslavsimek/be-294-oidc-problems-with-rdm12