Upgraded python version and requests
Narodni-repozitar/nr-docs pull request #167
Opened 2024-09-22 17:31 UTC by mesemus

2024-09-23 08:55 UTC, mirekys requested changes

2024-09-23 08:55 UTC, mirekys commented on documents/services/records/config.py
> +                if_=RecordLink("{+api}/docs/{id}/draft"),
Publish request accept action fails on non-existence of `_else` branch here

2024-09-23 08:55 UTC, mirekys commented on documents/services/records/config.py
> +                if_=RecordLink("{+ui}/docs/{id}/edit", when=has_draft),
ConditionalLink requires `else_` to be also defined

2024-10-18 12:39 UTC, SilvyPuzzlewell approved these changes

2024-10-18 12:44 UTC, SilvyPuzzlewell approved these changes

2024-10-18 15:00 UTC, SilvyPuzzlewell approved these changes

2024-10-18 15:03 UTC, merged